// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MTL/2.0/
// © chartbox90
//@version=5
indicator("QM Signal [TradingFinder] Quasimodo Pattern - Head and Shoulders", overlay = true , max_bars_back = 5000 , max_lines_count = 500 , max_labels_count = 500)


PP = input.int(5 , 'Pivot Period')
ATR = ta.atr(21)
var ArrayType = array.new_string()
var ArrayValue = array.new_float()
var ArrayIndex =  array.new_int()
var Line = array.new_line()

HighPivot = ta.pivothigh(PP,PP)
LowPivot = ta.pivotlow(PP,PP)

HighValue = ta.valuewhen(HighPivot ,high[PP], 0)
LowValue = ta.valuewhen(LowPivot ,low[PP], 0)

HighIndex = ta.valuewhen(HighPivot ,bar_index[PP], 0)
LowIndex = ta.valuewhen(LowPivot ,bar_index[PP], 0)

Correct_HighPivot = 0.0
Correct_LowPivot =  0.0

PASS = 0

if HighPivot  and  LowPivot
    if ArrayType.size() == 0
        PASS := 1
    else if ArrayType.size() >= 1
        if ((ArrayType.get(ArrayType.size() - 1)) == "L" or
             (ArrayType.get(ArrayType.size() - 1)) == "LL")
            if LowPivot < ArrayValue.get(ArrayType.size() - 1)
                array.remove(ArrayType,ArrayType.size() - 1)
                array.remove(ArrayValue,ArrayValue.size() - 1)
                array.remove(ArrayIndex,ArrayIndex.size() - 1) 
                array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < LowValue ? "HL" : "LL" : "L")///////////////////////////////Here
                array.push(ArrayValue, LowValue)
                array.push(ArrayIndex, LowIndex)
                Correct_LowPivot :=  LowValue
            else 
                array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < HighValue ? "HH" : "LH" : "H" ) ///////////////////////////////Here
                array.push(ArrayValue, HighValue)
                array.push(ArrayIndex, HighIndex)
            Correct_HighPivot := HighValue  
        else if (ArrayType.get(ArrayType.size() - 1)) == "H" or 
             (ArrayType.get(ArrayType.size() - 1)) == "HH"
            if HighPivot > ArrayValue.get(ArrayType.size() - 1)
                array.remove(ArrayType,ArrayType.size() - 1)
                array.remove(ArrayValue,ArrayValue.size() - 1)
                array.remove(ArrayIndex,ArrayIndex.size() - 1)
                array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < HighValue ? "HH" : "LH" : "H")///////////////////////////////Here
                array.push(ArrayValue, HighValue)
                array.push(ArrayIndex, HighIndex)
                Correct_HighPivot := HighValue  
            else 
                array.push(ArrayType,ArrayType.size()>2?  ArrayValue.get(ArrayType.size() - 2) < LowValue ? "HL" : "LL" : "L")///////////////////////////////Here
                array.push(ArrayValue, LowValue)
                array.push(ArrayIndex, LowIndex)
            Correct_LowPivot :=  LowValue    
        else if (ArrayType.get(ArrayType.size() - 1)) == "LH"
            if HighPivot < ArrayValue.get(ArrayType.size() - 1)
                array.push(ArrayType,ArrayType.size()>2?  ArrayValue.get(ArrayType.size() - 2) < LowValue ? "HL" : "LL" : "L")///////////////////////////////Here
                array.push(ArrayValue, LowValue)
                array.push(ArrayIndex, LowIndex)
                Correct_LowPivot :=  LowValue 
            else if HighPivot > ArrayValue.get(ArrayType.size() - 1)
                if close < ArrayValue.get(ArrayType.size() - 1)
                    array.remove(ArrayType,ArrayType.size() - 1)
                    array.remove(ArrayValue,ArrayValue.size() - 1)
                    array.remove(ArrayIndex,ArrayIndex.size() - 1)
                    array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < HighValue ? "HH" : "LH" : "H")///////////////////////////////Here
                    array.push(ArrayValue, HighValue)
                    array.push(ArrayIndex, HighIndex)
                    Correct_HighPivot := HighValue  
                else if close > ArrayValue.get(ArrayType.size() - 1)
                    array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < LowValue ? "HL" : "LL" : "L")///////////////////////////////Here
                    array.push(ArrayValue, LowValue)
                    array.push(ArrayIndex, LowIndex)
                    Correct_LowPivot :=  LowValue
        else if (ArrayType.get(ArrayType.size() - 1)) == "HL"
            if LowPivot > ArrayValue.get(ArrayType.size() - 1)
                array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < HighValue ? "HH" : "LH" : "H" ) ///////////////////////////////Here
                array.push(ArrayValue, HighValue)
                array.push(ArrayIndex, HighIndex)
                Correct_HighPivot := HighValue                       
            else if LowPivot < ArrayValue.get(ArrayType.size() - 1)
                if close > ArrayValue.get(ArrayType.size() - 1)
                    array.remove(ArrayType,ArrayType.size() - 1)
                    array.remove(ArrayValue,ArrayValue.size() - 1)
                    array.remove(ArrayIndex,ArrayIndex.size() - 1) 
                    array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < LowValue ? "HL" : "LL" : "L")///////////////////////////////Here
                    array.push(ArrayValue, LowValue)
                    array.push(ArrayIndex, LowIndex)
                    Correct_LowPivot :=  LowValue
                else if close < ArrayValue.get(ArrayType.size() - 1)
                    array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < HighValue ? "HH" : "LH" : "H")///////////////////////////////Here
                    array.push(ArrayValue, HighValue)
                    array.push(ArrayIndex, HighIndex)
                    Correct_HighPivot := HighValue                         
else if  HighPivot 
    if ArrayType.size() == 0
        array.insert(ArrayType, 0, "H")
        array.insert(ArrayValue, 0, HighValue)
        array.insert(ArrayIndex, 0, HighIndex)
        Correct_HighPivot := HighValue
    else if ArrayType.size() >= 1
        if ((ArrayType.get(ArrayType.size() - 1)) == "L" or
             (ArrayType.get(ArrayType.size() - 1)) == "HL" or
             (ArrayType.get(ArrayType.size() - 1)) == "LL")
            if HighPivot > ArrayValue.get(ArrayType.size() - 1)
                array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < HighValue ? "HH" : "LH" : "H" ) ///////////////////////////////Here
                array.push(ArrayValue, HighValue)
                array.push(ArrayIndex, HighIndex)
                Correct_HighPivot := HighValue
            else if  HighPivot < ArrayValue.get(ArrayType.size() - 1)
                array.remove(ArrayType,ArrayType.size() - 1)
                array.remove(ArrayValue,ArrayValue.size() - 1)
                array.remove(ArrayIndex,ArrayIndex.size() - 1) 
                array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < LowValue ? "HL" : "LL" : "L")///////////////////////////////Here
                array.push(ArrayValue, LowValue)
                array.push(ArrayIndex, LowIndex)
                Correct_LowPivot :=  LowValue                         
        else if (ArrayType.get(ArrayType.size() - 1)) == "H" or 
             (ArrayType.get(ArrayType.size() - 1)) == "HH" or 
             (ArrayType.get(ArrayType.size() - 1)) == "LH"
            if (ArrayValue.get(ArrayValue.size() - 1)) < HighValue
                array.remove(ArrayType,ArrayType.size() - 1)
                array.remove(ArrayValue,ArrayValue.size() - 1)
                array.remove(ArrayIndex,ArrayIndex.size() - 1)
                array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < HighValue ? "HH" : "LH" : "H")///////////////////////////////Here
                array.push(ArrayValue, HighValue)
                array.push(ArrayIndex, HighIndex)
                Correct_HighPivot := HighValue               
else if LowPivot 
    if ArrayType.size() == 0
        array.insert(ArrayType, 0, "L")
        array.insert(ArrayValue, 0, LowValue)
        array.insert(ArrayIndex, 0, LowIndex)
        Correct_LowPivot :=  LowValue
    else if ArrayType.size() >= 1
        if (ArrayType.get(ArrayType.size() - 1)) == "H" or 
             (ArrayType.get(ArrayType.size() - 1)) == "HH" or 
             (ArrayType.get(ArrayType.size() - 1)) == "LH"
            if LowPivot < ArrayValue.get(ArrayType.size() - 1)
                array.push(ArrayType,ArrayType.size()>2?  ArrayValue.get(ArrayType.size() - 2) < LowValue ? "HL" : "LL" : "L")///////////////////////////////Here
                array.push(ArrayValue, LowValue)
                array.push(ArrayIndex, LowIndex)
                Correct_LowPivot :=  LowValue
            else if LowPivot > ArrayValue.get(ArrayType.size() - 1)
                array.remove(ArrayType,ArrayType.size() - 1)
                array.remove(ArrayValue,ArrayValue.size() - 1)
                array.remove(ArrayIndex,ArrayIndex.size() - 1)
                array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < HighValue ? "HH" : "LH" : "H")///////////////////////////////Here
                array.push(ArrayValue, HighValue)
                array.push(ArrayIndex, HighIndex)
                Correct_HighPivot := HighValue                        
        else if (ArrayType.get(ArrayType.size() - 1)) == "L" or 
             (ArrayType.get(ArrayType.size() - 1)) == "HL" or 
             (ArrayType.get(ArrayType.size() - 1)) == "LL"
            if (ArrayValue.get(ArrayValue.size() - 1)) > LowValue
                array.remove(ArrayType,ArrayType.size() - 1)
                array.remove(ArrayValue,ArrayValue.size() - 1)
                array.remove(ArrayIndex,ArrayIndex.size() - 1) 
                array.push(ArrayType,ArrayType.size()>2? ArrayValue.get(ArrayType.size() - 2) < LowValue ? "HL" : "LL" : "L")///////////////////////////////Here
                array.push(ArrayValue, LowValue)
                array.push(ArrayIndex, LowIndex)
                Correct_LowPivot :=  LowValue

QMDetector()=>
    //Bearish QM

    var string TH1 = ""
    var string TH2 = ""
    var string TH3 = ""
    var string TH4 = ""
    var string TH5 = ""

    var int IH = 0
    var int IH1 = 0
    var int IH2 = 0
    var int IH3 = 0
    var int IH4 = 0
    var int IH5 = 0

    var float VH1 = 0.0
    var float VH2 = 0.0
    var float VH3 = 0.0
    var float VH4 = 0.0
    var float VH5 = 0.0

    var bool BearQM = false

    //Bullish QM

    var string TL1 = ""
    var string TL2 = ""
    var string TL3 = ""
    var string TL4 = ""
    var string TL5 = ""

    var int IL = 0
    var int IL1 = 0
    var int IL2 = 0
    var int IL3 = 0
    var int IL4 = 0
    var int IL5 = 0

    var float VL1 = 0.0
    var float VL2 = 0.0
    var float VL3 = 0.0
    var float VL4 = 0.0
    var float VL5 = 0.0

    var bool BullQM = false

    if ArrayType.size() > 5 
        TH1 := ArrayType.get(ArrayType.size() - 1)
        TH2 :=  ArrayType.get(ArrayType.size() - 2)
        TH3 :=  ArrayType.get(ArrayType.size() - 3)
        TH4 :=  ArrayType.get(ArrayType.size() - 4)
        TH5 :=  ArrayType.get(ArrayType.size() - 5)
        IH  := ArrayIndex.get(ArrayType.size() - 1)

        IH1 := ArrayIndex.get(ArrayType.size() - 1)
        IH2 := ArrayIndex.get(ArrayType.size() - 2)
        IH3 := ArrayIndex.get(ArrayType.size() - 3)
        IH4 := ArrayIndex.get(ArrayType.size() - 4)
        IH5 := ArrayIndex.get(ArrayType.size() - 5)

        VH1 := ArrayValue.get(ArrayType.size() - 1)
        VH2 := ArrayValue.get(ArrayType.size() - 2)
        VH3 := ArrayValue.get(ArrayType.size() - 3)
        VH4 := ArrayValue.get(ArrayType.size() - 4)
        VH5 := ArrayValue.get(ArrayType.size() - 5)

    if ArrayType.size() > 5 
        TL1 := ArrayType.get(ArrayType.size() - 1)
        TL2 := ArrayType.get(ArrayType.size() - 2)
        TL3 := ArrayType.get(ArrayType.size() - 3)
        TL4 := ArrayType.get(ArrayType.size() - 4)
        TL5 := ArrayType.get(ArrayType.size() - 5)

        IL  := ArrayIndex.get(ArrayType.size() - 1)
        IL1 := ArrayIndex.get(ArrayType.size() - 1)
        IL2 := ArrayIndex.get(ArrayType.size() - 2)
        IL3 := ArrayIndex.get(ArrayType.size() - 3)
        IL4 := ArrayIndex.get(ArrayType.size() - 4)
        IL5 := ArrayIndex.get(ArrayType.size() - 5)

        VL1 := ArrayValue.get(ArrayType.size() - 1)
        VL2 := ArrayValue.get(ArrayType.size() - 2)
        VL3 := ArrayValue.get(ArrayType.size() - 3)
        VL4 := ArrayValue.get(ArrayType.size() - 4)
        VL5 := ArrayValue.get(ArrayType.size() - 5)

    //Bearish QM
    var BearQM_Start = 0.0
    var BearQM_End = 0.0
    var BearQM_Index = 0.0
    var CheckBe = 0
    if TH1 == "LL" and  TH2 == "HH" and TH3 == "HL" and TH4 == "HH"  and VH5 < VH1 and IH == (bar_index - PP) and CheckBe == 0
        BearQM := true
        BearQM_Start := VH2
        BearQM_End := VH1
        BearQM_Index := IH
        CheckBe := 1 
    else
        BearQM := false
    if BearQM_Start != VH2
        CheckBe := 0


    //Bullish QM
    var BullQM_Start = 0.0
    var BullQM_End = 0.0
    var BullQM_Index = 0
    var CheckBu = 0
    if  TL1 == "HH" and TL2 == "LL" and TL3 == "LH" and TL4 == "LL" and VL5 > VL1 and  IL == bar_index - PP and CheckBu == 0 
        BullQM := true
        BullQM_Start := VL2
        BullQM_End := VL1
        BullQM_Index := IL
        CheckBu := 1
    else
        BullQM := false

    if BullQM_Start != VL2
        CheckBu := 0

    var line BuLeg1 = na
    var line BuLeg2 = na
    var line BuLeg3 = na
    var line BuLeg4 = na
    var line BuLeg5 = na
    var line BuEntryLine= na    
    var line BuSLLine   = na
    var line BuTP1Line  = na
    var line BuTP2Line  = na
    var label BuEntryLabel= na    
    var label BuSLLabel   = na
    var label BuTP1Label  = na
    var label BuTP2Label  = na 
    BuMove  = (IL2 - IL4) /2

    var line BeLeg1 = na
    var line BeLeg2 = na
    var line BeLeg3 = na
    var line BeLeg4 = na
    var line BeLeg5 = na
    var line BeEntryLine= na
    var line BeSLLine   = na
    var line BeTP1Line  = na
    var line BeTP2Line  = na
    var label BeEntryLabel= na
    var label BeSLLabel   = na
    var label BeTP1Label  = na
    var label BeTP2Label  = na
    BeMove  = (IH2 - IH4) /2
    
    if BullQM
        // BuMove := (IL2 - IL5) * 2 + 6
        BuLeg1 := line.new(IL5 , VL5 , IL4 , VL4, color = color.rgb(38, 150, 41) , width = 2)
        BuLeg2 := line.new(IL4 , VL4 , IL3 , VL3, color = color.rgb(38, 150, 41) , width = 2)
        BuLeg3 := line.new(IL3 , VL3 , IL2 , VL2, color = color.rgb(38, 150, 41) , width = 2)
        BuLeg4 := line.new(IL2 , VL2 , IL1 , VL1, color = color.rgb(38, 150, 41) , width = 2)
        BuLeg5 := line.new(IL1 , VL1 , IL1 + BuMove-2 , VL4, color = color.rgb(4, 215, 252) , width = 2 , style = line.style_arrow_right)
        BuEntryLine:= line.new(IL4 , VL4 , IL1 + BuMove , VL4, color = color.rgb(0, 0, 0) , width = 1 , style = line.style_dotted)
        BuSLLine   := line.new(IL2  , VL2- (ATR/2) , IL1 + BuMove , VL2 - (ATR/2), color = color.rgb(170, 29, 29), width = 1, style = line.style_dotted)
        BuTP1Line  := line.new(IL3 , VL3 , IL1 + BuMove , VL3, color = color.rgb(91, 172, 74) , width = 1, style = line.style_dotted)
        BuTP2Line  := line.new(IL1 , VL1 , IL1 + BuMove , VL1, color = color.rgb(91, 172, 74) , width = 1, style = line.style_dotted) 
        BuEntryLabel:= label.new(IL1 + BuMove+1 , VL4 , 'Entry' , color = color.rgb(255, 255, 255, 100) , style = label.style_text_outline )
        BuSLLabel   := label.new(IL1 + BuMove+1 , VL2- (ATR/2) , 'SL' , color = color.rgb(255, 255, 255, 100) , style = label.style_text_outline )
        BuTP1Label  := label.new(IL1 + BuMove+1 , VL3 , 'TP1' , color = color.rgb(255, 255, 255, 100) , style = label.style_text_outline )
        BuTP2Label  := label.new(IL1 + BuMove+1 , VL1 , 'TP2' , color = color.rgb(255, 255, 255, 100) , style = label.style_text_outline )

    if BearQM
        BeLeg1 := line.new(IH5 , VH5 , IH4 , VH4, color = color.rgb(170, 29, 29) , width = 2)
        BeLeg2 := line.new(IH4 , VH4 , IH3 , VH3, color = color.rgb(170, 29, 29) , width = 2)
        BeLeg3 := line.new(IH3 , VH3 , IH2 , VH2, color = color.rgb(170, 29, 29) , width = 2)
        BeLeg4 := line.new(IH2 , VH2 , IH1 , VH1, color = color.rgb(170, 29, 29) , width = 2)
        BeLeg5 := line.new(IH1 , VH1 , IH1 + BeMove-2 , VH4, color = color.rgb(252, 173, 4) , width = 2 , style = line.style_arrow_right)
        BeEntryLine:= line.new(IH4 , VH4 , IH1 + BeMove , VH4, color = color.rgb(0, 0, 0) , width = 1 , style = line.style_dotted)
        BeSLLine   := line.new(IH2  , VH2+ (ATR/2) , IH1 + BeMove , VH2 + (ATR/2), color = color.rgb(170, 29, 29), width = 1, style = line.style_dotted)
        BeTP1Line  := line.new(IH3 , VH3 , IH1 + BeMove , VH3, color = color.rgb(91, 172, 74) , width = 1, style = line.style_dotted)
        BeTP2Line  := line.new(IH1 , VH1 , IH1 + BeMove , VH1, color = color.rgb(91, 172, 74) , width = 1, style = line.style_dotted) 
        BeEntryLabel:= label.new(IH1 + BeMove+1 , VH4 , 'Entry' , color = color.rgb(255, 255, 255, 100) , style = label.style_text_outline )
        BeSLLabel   := label.new(IH1 + BeMove+1 , VH2+ (ATR/2) , 'SL' , color = color.rgb(255, 255, 255, 100) , style = label.style_text_outline )
        BeTP1Label  := label.new(IH1 + BeMove+1 , VH3 , 'TP1' , color = color.rgb(255, 255, 255, 100) , style = label.style_text_outline )
        BeTP2Label  := label.new(IH1 + BeMove+1 , VH1 , 'TP2' , color = color.rgb(255, 255, 255, 100) , style = label.style_text_outline )


QMDetector()